#!/bin/bash
# upgrade installed helm by using localy 
# "make helm" and  "helm upgrade"
# Version is used from .next-version
# .next-version: 
# release next-version --allow-current > .next-version
# TODO add automaticaly deploy to each environment (menu) with correct host
# value (ingress.host)
exec 5>&1
SEPARATOR="--------------------------------------------------------------------------------"
# version=$(git tag --sort=-committerdate | head -n 1)
# version=${version:1}
version=$(cat .next-version) # the same as in the Makefile
echo "$SEPARATOR" 
echo "1. Create helm version $version"
# exmple:
# Successfully packaged chart and saved it to: dist/sensor-simulator-1.4.1.tgz
REGEXP="Successfully packaged chart.*:[[:space:]](dist/(.*)\-[0-9]*\..*\.tgz)"
# version can be overrided
result=$(make helm VERSION=$version | tee >(cat - >&5) | tail -1)
[[ $result =~ $REGEXP ]] 
chart="${BASH_REMATCH[1]}"
release="${BASH_REMATCH[2]}"
echo "$SEPARATOR" 
if [ -n "$chart" ]; then 
    echo "2. Starting upgrade $release deployment with $chart"
    if [ -n "$2" ]; then
        namespace="-n $2"
    fi
    helm upgrade $release $chart --set ingress.host=$1 $namespace 
else
    echo "2. Creating chart is failed so helm is not upgraded: ${result}"
fi
